config/routes.rb
Rails.application.routes.draw do

  root 'product#index'
  devise_for :users

  resources :product do
    member do
      get 'carts/new'
      # get 'addcart'
    end
    resources :carts
  end

  resources :carts do
    collection do
      get 'checkout'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :weight ,:weight_type ,:quantity ,presence: :true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,:trackable
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  private
  def login_check
    if !user_signed_in?
      flash[:notice] = "You need to Sing In first"
      redirect_to(root_path)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :login_check
  def index
    # @cart = Cart.all
    sql = "select * from carts JOIN products ON carts.product_id = products.id
    WHERE carts.user_id = #{current_user.id}"
    @cart =  ActiveRecord::Base.connection.execute(sql)
  end
  def new
    @product =Product.find(params[:id])

  end
  def checkout
    sql = "select * from carts JOIN products ON carts.product_id = products.id
    WHERE carts.user_id = #{current_user.id}"
    @cart =  ActiveRecord::Base.connection.execute(sql)
  end

  def create
    puts params[:product_id]
    puts params[:weight]
    @product = Product.find(params[:product_id])
    puts cart_params
    @cart = @product.carts.create(cart_params)
    redirect_to root_path
  end

  private
  def cart_params
    current_user.id
    params.require(:cart).permit(:weight, :weight_type,:quantity,:user_id)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :login_check ,only:[:show]

  def index
    @product = Product.all
  end
  def show
    @product =Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper

  def total_price(weight,type,quantity,price)
    if type == "G"
      x = weight.to_f
      total = price*quantity*(x/1000)

      total
    else
      weight*quantity*price
    end
  end
  def sum_total(cart)
     sum_1(cart)
  end

  def tax(cart)
    x = sum_1(cart)
    (x*10)/100
  end
  def total_to_pay(cart)
    sum_1(cart) + tax(cart)
  end
  private
  def sum_1(cart)
    sum = 0
    cart.each do |x|
      if x["weight_type"]  == "G"
        xx = x["weight"].to_f
        sum += (xx/1000)*x["quantity"]*x["price_per_kg"]
      else
        sum += x["weight"]*x["quantity"]*x["price_per_kg"]
      end
    end
    return sum
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/carts/checkout.html.erb
<% if user_signed_in? %>
    <h2><%= current_user.email %></h2>
  <% end %>
<h3>Place Order</h3>
  <table class="table">
    <tr>
      <th>item</th>
      <th>Weight</th>
      <th>quantity</th>
      <th>Price per Kg</th>
      <th>total price</th>
    </tr>

    <% @cart.each do |x|%>
      <tr>
      <td><%= x["name"]%></td>
      <td><%= x["weight"] %><%= x["weight_type"] %></td>
      <td><%= x["quantity"]%></td>
      <td><%= x["price_per_kg"]%></td>
      <td><%= total_price(x["weight"],x["weight_type"],x["quantity"],x["price_per_kg"]) %></td>


      </tr>

    <% end %>

    <tr>
      <td colspan="4"></td>

      <th><%= sum_total(@cart)%></th>
    </tr>
    <tr>
      <td colspan="3"></td>
      <th>Tax(10%)</th>
      <td><%= tax(@cart)%></td>
    </tr>
    <tr>
      <td colspan="3"></td>
      <th>Total to pay</th>
      <th><%= total_to_pay(@cart)%></th>
    </tr>
  </table>

app/views/carts/index.html.erb
<% if user_signed_in? %>
    <h2><%= current_user.email %></h2>
  <% end %>
<h3>My Cart</h3>
  <table class="table">
    <tr>
      <th>item</th>
      <th>Weight</th>
      <th>quantity</th>
      <th>Price per Kg</th>
      <th>total price</th>
    </tr>

    <% @cart.each do |x|%>
      <tr>
      <td><%= x["name"]%></td>
      <td><%= x["weight"] %><%= x["weight_type"] %></td>
      <td><%= x["quantity"]%></td>
      <td><%= x["price_per_kg"]%></td>
      <td><%= total_price(x["weight"],x["weight_type"],x["quantity"],x["price_per_kg"]) %></td>


      </tr>

    <% end %>


    <tr>
      <td><%= link_to "checkout",checkout_carts_path %></td>
    </tr>
  </table>
  <h6><%= link_to "home",root_path%></h6>

app/views/carts/new.html.erb
  <% if user_signed_in? %>
    <h2><%= current_user.email %></h2>
  <% end %>
  <h2><%= @product.name%></h2>
  <%= form_with model: [@product] do |form| %>
  <p>
    <%= form.label :name %><br>

    <input type="text" value="<%= @product.name %>" name="product[name]" id="product_name" readonly>
  </p>

  <p>
    <%= form.label :price_per_kg %><br>
    <input type="number" value="<%= @product.price_per_kg %>" name="product[price_per_kg]" id="product_price_per_kg" readonly>
  </p>

  <p>
    <%= form.label :weight ,"Package Weight" %><br>
    <%= form.select :weight, [100,250, 500,1] %>
    <%= form.radio_button :weight_type, "G" %>
    <%= form.label :weight_type_g, "G" %>
    <%= form.radio_button :weight_type, "Kg" %>
    <%= form.label :weight_type_kg, "Kg" %>

  </p>

  <p>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity  %>
  </p>
  <p>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :product_id, value: @product.id %>
  </p>
  <p>
    <%= form.submit "Add to Cart"%>
  </p>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">


    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <% if user_signed_in? %>
      <%= link_to 'Sing Out',destroy_user_session_path, data:{turbo_method: :delete} %>
    <% else %>
      <%= link_to 'Sing In',new_user_session_path %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/product/index.html.erb
<% if user_signed_in? %>
    <h2><%= current_user.email %></h2>

  <% end %>
  <h1>Poduct details</h1>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Price per kg</th>
      <th colspan="2"></th>
    </tr>
    <% @product.each do |p|%>
    <tr>

      <td><%= p.name%></td>
      <td><%= p.price_per_kg%></td>
      <td><%= link_to "Add to Cart",product_path(p)%></td>
      

    </tr>
    <% end %>
  </table>
  <h4><%= link_to "Go to cart",carts_path%></h4>

app/views/product/show.html.erb
<% if user_signed_in? %>
  <h2><%= current_user.email %></h2>
<% end %>
<h2><%= @product.name%></h2>
<%= form_with model: [@product,@product.carts.build] do |form| %>
<p>
  <%= form.label :name %><br>

  <input type="text" value="<%= @product.name %>" name="product[name]" id="product_name" readonly>
</p>

<p>
  <%= form.label :price_per_kg %><br>
  <input type="number" value="<%= @product.price_per_kg %>" name="product[price_per_kg]" id="product_price_per_kg" readonly>
</p>

<p>
<p>
  <%= form.label :weight ,"Package Weight" %><br>
  <%= form.select :weight, [100,250, 500,1] %>
  <%= form.radio_button :weight_type, "G" %>
  <%= form.label :weight_type_g, "G" %>
  <%= form.radio_button :weight_type, "Kg" %>
  <%= form.label :weight_type_kg, "Kg" %>

</p>

<p>
  <%= form.label :quantity %><br>
  <%= form.number_field :quantity  %>
</p>
<p>

</p><%= form.hidden_field :user_id, value: current_user.id %>
<p>
  <%= form.submit "Add to Cart"%>
</p>
<% end %>
<h6><%= link_to "home",root_path%></h6>